中核のドメインモデルを整理しなおす
ChenCMD/Shapes-Generator-v2 pull request #7
Opened 2022-01-30 04:28 UTC by kory33

2022-02-02 22:08 UTC, kory33 commented
必要な概念は大体定義しました。ModifierとShapeはそれぞれ[ここ](https://github.com/ChenCMD/Shapes-Generator-v2/tree/7591220c5296e41ce7c6bba7d9bc985787667b6e/src/sgp/definition/Modifiers)と[ここ](https://github.com/ChenCMD/Shapes-Generator-v2/tree/redesign-attempt-2/src/sgp/definition/ShapeObjects)に定義されることを想定しています(現状Patchの仕組みがほぼほぼボイラープレートなので、`new`-type に対するジェネリックなプログラミングで何とかした方がいいかもとは思っています）。

2022-02-12 20:29 UTC, kory33 commented
> 必要な概念は大体定義しました。ModifierとShapeはそれぞれ[ここ](https://github.com/ChenCMD/Shapes-Generator-v2/tree/7591220c5296e41ce7c6bba7d9bc985787667b6e/src/sgp/definition/Modifiers)と[ここ](https://github.com/ChenCMD/Shapes-Generator-v2/tree/redesign-attempt-2/src/sgp/definition/ShapeObjects)に定義されることを想定しています(現状Patchの仕組みがほぼほぼボイラープレートなので、`new`-type に対するジェネリックなプログラミングで何とかした方がいいかもとは思っています）。

これは  983b8e7 で解決済み

2022-07-17 21:09 UTC, ChenCMD requested changes
`Object.assign`を使用してる箇所はスプレッド構文に書き換えるとよりスマートに思えますが、まぁどちらでもよさそう。

あとはフォーマットが整ってないのが気になるくらいです

2022-07-17 21:09 UTC, ChenCMD commented on src/sgp/interpreter/interpreter.test.ts
> +      ] },
139-153行目のオブジェクトとUid以外変わらないのは意図してますか

2022-09-18 17:26 UTC, kory33 commented
五億年ぶりに覗きました　今夜中にレビュー対応します！

2022-09-18 20:29 UTC, kory33 commented on src/sgp/definition/ShapeObjects/Ellipse.ts
> +};
この辺は PoC として作ってるのでこの PR で定義を完璧にする意図は無いです。必要なら他の PR で対応して下さい 🙏

2022-09-18 20:30 UTC, kory33 commented on src/sgp/interpreter/phases/diff-expansion.ts
> +      const syncDef: SynchronizedShape = shapeObject;
たし🦀

2022-09-18 20:31 UTC, kory33 commented on src/sgp/interpreter/phases/diff-expansion.ts
> +      const syncDef: SynchronizedShape = shapeObject;
[244fe82](https://github.com/ChenCMD/Shapes-Generator-v2/pull/7/commits/244fe825d2fd5b08d9c95b27fb89899ee0b01543)

2022-09-18 20:32 UTC, kory33 commented on src/sgp/interpreter/phases/diff-expansion.ts
> +      const target = targetCandidates[0]!;
これはどちらかというと人間向けですね。無くても動きますが、あっても良いものだと思っています。

2022-09-18 20:34 UTC, kory33 commented on src/sgp/interpreter/interpreter.test.ts
> +      ] },
テストケース側のミスでした！ [917619c](https://github.com/ChenCMD/Shapes-Generator-v2/pull/7/commits/917619c2c8a02575b7de23f6d4cd3af44e0b0c38)

2022-09-18 20:41 UTC, kory33 commented
@ChenCMD 再レビューお願いします。 `Object.assign` はスプレッド構文に置き換えました。

フォーマットに関しては、 prettier みたいなのを入れて、設定ファイルで全部制御しつつ CI でチェックするようにしてもらうなどすると捗るかもしれません

2022-09-24 06:56 UTC, kory33 commented
フォーマットは #19 により強制されるようになりました（ CI で lint check してもいいかも）

2022-09-24 07:18 UTC, kory33 commented on src/sgp/interpreter/phases/diff-expansion.ts
> +      const target = targetCandidates[0]!;
あー、 non-null-assertion は今見ると要らないかも　消します

2022-09-24 07:19 UTC, kory33 commented on src/sgp/interpreter/phases/diff-expansion.ts
> +      const target = targetCandidates[0]!;
bcb4328

2022-09-24 16:10 UTC, ChenCMD approved these changes

2022-09-24 16:10 UTC, merged